### ISSUE TITLE
Some names are not parsed safely

### ISSUE THREAD

**Issue by HardBlock729** [phatcher/Meerkat.NameParser#4]
Given the name "Ma Tal Simpson" this error is thrown:
```
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Meerkat.Party.Naming.PersonNameParser.ConstructName()
   at Meerkat.Party.Naming.PersonNameParser.Parse(String name, IName person, String format)
   at Meerkat.Party.Naming.PersonName.Parse(String value, String format)
```
This error seems related to the "Ma" and the beginning of the name. When the "Ma" is removed the name parses correctly.

**Comment by phatcher** [comment]
I'll take a look

**Comment by HardBlock729** [comment]
@phatcher I forgot to note that we are on version 1.1.1 running in a .NET Core 3.1 ASP.NET MVC application.
